const appList = [
    { title: 'About', icon: '👤', path: '../../app/about/index.html' },
    { title: 'Blocks', icon: '🧱', path: '../../app/blocks/index.html' },
    { title: 'Calculator', icon: '🔢', path: '../../app/calculator/index.html' },
    { title: 'Chat', icon: '💬', path: '../../app/chat/index.html' },
    { title: 'Chess', icon: '♟️', path: '../../app/chess/index.html' },
    { title: 'Games', icon: '🎮', path: '../../app/games/index.html' },
    { title: 'Maps', icon: '🗺️', path: '../../app/maps/index.html' },
    { title: 'Notepad', icon: '📝', path: '../../app/notepad/index.html' },
    { title: 'Player', icon: '🎬', path: '../../app/player/index.html' },
    { title: 'Stopwatch', icon: '⌚', path: '../../app/stopwatch/index.html'},
    { title: 'Superbirdjumper3', icon: '🐦', path: '../../app/superbirdjumper3/index.html' },
    { title: 'Tictactoe', icon: '🌀', path: '../../app/tictactoe/index.html'},
    { title: 'Ultraraccoon', icon: '🦝', path: '../../app/ultraraccoon/index.html'},
    { title: 'Weather', icon: '⛅', path: '../../app/weather/index.html'},
];
