const sources = [
    { name: "12 MiniBattles", slug: "12-minibattles" },
{ name: "2048", slug: "0-2048" },
{ name: "8 Ball Pool", slug: "0-8-ball-pool" },
{ name: "A Small World Cup", slug: "a-small-world-cup" },
{ name: "Air Wars 3", slug: "air-wars-3" },
{ name: "Apple Worm", slug: "0-apple-worm" },
{ name: "Awesome Tanks 2", slug: "0-awesome-tanks-2" },
{ name: "Basket Random", slug: "basket-random" },
{ name: "Basketball Stars", slug: "basketball-stars" },
{ name: "Big Tower Square", slug: "0-big-tower-tiny-square" },
{ name: "Biker Street", slug: "0-biker-street" },
{ name: "Bloons Adventure", slug: "0-bloons-adventure-time-td" },
{ name: "Bloxorz", slug: "0-bloxorz" },
{ name: "Blue", slug: "0-blue" },
{ name: "Bob the Robber", slug: "0-bob-the-robber" },
{ name: "Boxing Random", slug: "boxing-random" },
{ name: "BuildNow GG", slug: "buildnow-gg" },
{ name: "Bullet Force", slug: "bullet-force" },
{ name: "Bumper Cars", slug: "bumper-cars-soccer" },
{ name: "Burnin' Rubber 5 XS", slug: "burnin-rubber-5-xs" },
{ name: "Chess", slug: "0-chess" },
{ name: "Copter Royale", slug: "0-copter-royale" },
{ name: "Crazy Cars", slug: "crazy-cars" },
{ name: "Crossy Road", slug: "crossy-road" },
{ name: "Cyber Cars Punk", slug: "cyber-cars-punk-racing" },
{ name: "Cyber Chaser", slug: "cyber-chaser" },
{ name: "Death Run", slug: "death-run-3d" },
{ name: "Diggy", slug: "0-diggy" },
{ name: "Doodle Jump", slug: "doodle-jump" },
{ name: "Drift Hunters", slug: "drift-hunters" },
{ name: "Drive Mad", slug: "drive-mad" },
{ name: "Drunken Boxing", slug: "drunken-boxing" },
{ name: "Duck Life 4", slug: "0-duck-life-4" },
{ name: "Eggy Party", slug: "eggy-party" },
{ name: "Elastic Man", slug: "elastic-man" },
{ name: "EvoWorld.io", slug: "evoworld-io" },
{ name: "Fireboy & Watergirl", slug: "0-fireboy-and-watergirl-in-the-forest-temple" },
{ name: "Firefall", slug: "firefall" },
{ name: "Football Legends", slug: "football-legends-2021" },
{ name: "Funny Shooter 2", slug: "funny-shooter-2" },
{ name: "Geometry Dash", slug: "geometry-dash-lite" },
{ name: "Getaway Shootout", slug: "getaway-shootout" },
{ name: "Grand City Missions", slug: "grand-city-missions" },
{ name: "Grindcraft", slug: "0-grindcraft" },
{ name: "G-Switch 3", slug: "g-switch-3" },
{ name: "Hangman", slug: "0-hangman" },
{ name: "Happy Wheels", slug: "happy-wheels" },
{ name: "Hexanaut.io", slug: "0-hexanaut-io" },
{ name: "House of Hazards", slug: "house-of-hazards" },
{ name: "Idle Breakout", slug: "0-idle-breakout" },
{ name: "Idle Dice", slug: "0-idle-dice" },
{ name: "Idling Lumberjack", slug: "idling-lumberjack-3d" },
{ name: "Impossible Quiz", slug: "0-the-impossible-quiz" },
{ name: "Janissary Tower", slug: "janissary-tower" },
{ name: "Jelly Truck", slug: "0-jelly-truck" },
{ name: "Johnny Upgrade", slug: "0-johnny-upgrade" },
{ name: "Krunker.io", slug: "krunker-io" },
{ name: "Learn to Fly 2", slug: "0-learn-to-fly-2" },
{ name: "Madalin Stunt Cars 2", slug: "madalin-stunt-cars-2" },
{ name: "Master Chess", slug: "master-chess" },
{ name: "Maze Baller", slug: "0-maze-baller" },
{ name: "Mind Games", slug: "mind-games-for-2-player" },
{ name: "Minecraft Classic", slug: "minecraft-classic" },
{ name: "Monster Tracks", slug: "monster-tracks" },
{ name: "Moto X3M", slug: "moto-x3m" },
{ name: "OvO", slug: "0-ovo" },
{ name: "Papa's Pizzeria", slug: "0-papas-pizzeria" },
{ name: "Parking Fury 2", slug: "0-parking-fury-2" },
{ name: "Penalty Kick", slug: "0-penalty-kick-online" },
{ name: "Pixel Battles", slug: "pixel-battles" },
{ name: "Powerline.io", slug: "0-powerline-io" },
{ name: "Quatro", slug: "0-quatro" },
{ name: "Racing Limits", slug: "racing-limits" },
{ name: "Ragdoll Archers", slug: "ragdoll-archers" },
{ name: "Retro Bowl", slug: "retro-bowl-26" },
{ name: "Rooftop Snipers", slug: "rooftop-snipers" },
{ name: "Run 3", slug: "0-run-3" },
{ name: "Shell Shockers", slug: "shell-shockers" },
{ name: "Slope", slug: "slope" },
{ name: "Smash Karts", slug: "smash-karts" },
{ name: "Soccer Random", slug: "soccer-random" },
{ name: "Solitaire", slug: "0-solitaire" },
{ name: "Space Waves", slug: "space-waves" },
{ name: "Stickman Archery", slug: "stickman-archery" },
{ name: "Stickman Hook", slug: "stickman-hook" },
{ name: "Stickman Temple", slug: "stickman-temple-maze" },
{ name: "Subway Surfers", slug: "subway-surfers" },
{ name: "Suika Watermelon", slug: "0-suika-watermelon-game" },
{ name: "Super Star Car", slug: "super-star-car" },
{ name: "Table Tennis World Tour", slug: "0-table-tennis-world-tour" },
{ name: "Tank Mayhem", slug: "tank-mayhem" },
{ name: "Temple Run 2", slug: "temple-run-2" },
{ name: "Thumb Fighter", slug: "thumb-fighter" },
{ name: "Tiny Fishing", slug: "0-tiny-fishing" },
{ name: "Two Ball 3D", slug: "two-ball-3d" },
{ name: "Ultimate Chess", slug: "ultimate-chess" },
{ name: "Vex 7", slug: "vex-7" },
{ name: "Vortelli's Pizza", slug: "vortellis-pizza" },
{ name: "World's Hardest Game", slug: "0-the-worlds-hardest-game" },
{ name: "Zombie Mission 10", slug: "zombie-mission-10" }
];
