const languages = [
    { name: 'Afrikaans', code: 'af' }, { name: 'Albanian', code: 'sq' },
{ name: 'Arabic', code: 'ar' }, { name: 'Armenian', code: 'hy' },
{ name: 'Basque', code: 'eu' }, { name: 'Bengali', code: 'bn' },
{ name: 'Bulgarian', code: 'bg' }, { name: 'Catalan', code: 'ca' },
{ name: 'Chinese (Simp)', code: 'zh-CN' }, { name: 'Chinese (Trad)', code: 'zh-TW' },
{ name: 'Croatian', code: 'hr' }, { name: 'Czech', code: 'cs' },
{ name: 'Danish', code: 'da' }, { name: 'Dutch', code: 'nl' },
{ name: 'English', code: 'en' }, { name: 'Estonian', code: 'et' },
{ name: 'Farsi', code: 'fa' }, { name: 'Filipino', code: 'tl' },
{ name: 'Finnish', code: 'fi' }, { name: 'French', code: 'fr' },
{ name: 'Galician', code: 'gl' }, { name: 'Georgian', code: 'ka' },
{ name: 'German', code: 'de' }, { name: 'Greek', code: 'el' },
{ name: 'Gujarati', code: 'gu' }, { name: 'Haitian Creole', code: 'ht' },
{ name: 'Hebrew', code: 'iw' }, { name: 'Hindi', code: 'hi' },
{ name: 'Hungarian', code: 'hu' }, { name: 'Icelandic', code: 'is' },
{ name: 'Indonesian', code: 'id' }, { name: 'Irish', code: 'ga' },
{ name: 'Italian', code: 'it' }, { name: 'Japanese', code: 'ja' },
{ name: 'Kannada', code: 'kn' }, { name: 'Korean', code: 'ko' },
{ name: 'Latin', code: 'la' }, { name: 'Latvian', code: 'lv' },
{ name: 'Lithuanian', code: 'lt' }, { name: 'Macedonian', code: 'mk' },
{ name: 'Malay', code: 'ms' }, { name: 'Maltese', code: 'mt' },
{ name: 'Norwegian', code: 'no' }, { name: 'Polish', code: 'pl' },
{ name: 'Portuguese', code: 'pt' }, { name: 'Romanian', code: 'ro' },
{ name: 'Russian', code: 'ru' }, { name: 'Serbian', code: 'sr' },
{ name: 'Slovak', code: 'sk' }, { name: 'Slovenian', code: 'sl' },
{ name: 'Spanish', code: 'es' }, { name: 'Swahili', code: 'sw' },
{ name: 'Swedish', code: 'sv' }, { name: 'Tamil', code: 'ta' },
{ name: 'Telugu', code: 'te' }, { name: 'Thai', code: 'th' },
{ name: 'Turkish', code: 'tr' }, { name: 'Ukrainian', code: 'uk' },
{ name: 'Urdu', code: 'ur' }, { name: 'Vietnamese', code: 'vi' },
{ name: 'Welsh', code: 'cy' }, { name: 'Yiddish', code: 'yi' }
];
