const appList = [
    { title: 'About', icon: '👤', path: '../about/index.html' },
    { title: 'Blocks', icon: '🧱', path: '../blocks/index.html' },
    { title: 'Calculator', icon: '🔢', path: '../calculator/index.html' },
    { title: 'Camera', icon: '📷', path: '../camera/index.html' },
    { title: 'Chat', icon: '💬', path: '../chat/index.html' },
    { title: 'Chess', icon: '♟️', path: '../chess/index.html' },
    { title: 'Clock', icon: '⏰', path: '../clock/index.html'},
    { title: 'Controls', icon: '🎛️', path: '../controls/index.html' },
    { title: 'Converter', icon: '➡️', path: '../converter/index.html' },
    { title: 'Fallpiece', icon: '🧩', path: '../fallpiece/index.html' },
    { title: 'Files', icon: '📁', path: '../files/index.html' },
    { title: 'Gallery', icon: '🖼️', path: '../gallery/index.html' },
    { title: 'Links', icon: '🔗', path: '../links/index.html' },
    { title: 'Maps', icon: '🗺️', path: '../maps/index.html' },
    { title: 'News', icon: '📰', path: '../news/index.html' },
    { title: 'Notepad', icon: '📝', path: '../notepad/index.html' },
    { title: 'Player', icon: '🎬', path: '../player/index.html' },
    { title: 'Pong', icon: '🏓', path: '../pong/index.html' },
    { title: 'Qr', icon: '🔳', path: '../qr/index.html' },
    { title: 'Query', icon: '🚀', path: '../query/index.html' },
    { title: 'Recorder', icon: '🎥', path: '../recorder/index.html' },
    { title: 'Snake', icon: '🐍', path: '../snake/index.html' },
    { title: 'Superbirdjumper3', icon: '🐦', path: '../superbirdjumper3/index.html' },
    { title: 'Synthesizer', icon: '🎹', path: '../synthesizer/index.html' },
    { title: 'Tictactoe', icon: '🌀', path: '../tictactoe/index.html'},
    { title: 'Translate', icon: '🌐', path: '../translate/index.html' },
    { title: 'Weather', icon: '⛅', path: '../weather/index.html'},
];
